---
version: '3.8'
services:
  swapi:
    init: true
    build:
      context: .
      dockerfile: .devops/docker/swapi/Dockerfile
    expose:
      - 8000
    volumes:
      - "./swapi:/app"

  db:
    image: "postgres:13"
    volumes:
      - ./shared/postgresql:/var/lib/postgresql/data
    environment:
      # set `${PGDATA}` to a subfolder because PostgreSQL needs this directory
      # to be empty, and there is already `.gitkeep` file there
      - PGDATA=/var/lib/postgresql/data/pgdata

  app:
    init: true
    build:
      context: .
      dockerfile: ./.devops/docker/backend/Dockerfile
    volumes:
      - ./backend:/app
      - ./shared/static:/app/shared/static:cached
      - ./shared/templates:/app/shared/templates:cached
    depends_on:
      - db

  web:
    init: true
    build:
      context: .
      dockerfile: ./.devops/docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
