# Generated by Django 3.1 on 2020-09-01 08:28
import django.core.validators

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    initial = True
    dependencies = []  # type: ignore[var-annotated]
    operations = [
        migrations.CreateModel(
            name='PeopleCollection',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        upload_to=(
                            'collections/people/%Y/%m/%d/'  # noqa: WPS323
                        ),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=('csv',),
                            ),
                        ],
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ('-created_at',)},
        ),
    ]
