"""Local settings for the project."""

from config.settings.base import *

# SECRET KEY
SECRET_KEY = env(
    'DJANGO_SECRET_KEY',
    default='local__5%3t4wf4^sl(#pm4)&-nlvpq%85vz=##@o$o5)vonby_jsyn7*',
)


# DEBUG
DEBUG = env.bool('DJANGO_DEBUG', default=True)
TEMPLATES[0]['OPTIONS']['debug'] = DEBUG


# CACHING
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': '',
    },
}


# HTTP
ALLOWED_HOSTS.extend([
    'localhost',
    '127.0.0.1',
    '[::1]',
])


# STATIC
STATIC_ROOT = str(APPS_DIR.path('shared/static_files'))


# DJANGO EXTENSIONS
INSTALLED_APPS.append('django_extensions')
IPYTHON_ARGUMENTS = env.list('IPYTHON_ARGUMENTS', default=[])


# DJANGO CORS HEADERS
CORS_ORIGIN_ALLOW_ALL = True


# DJANGO TEST MIGRATIONS
# install Django check that produces warnings for all migrations with
# autogenerated names
INSTALLED_APPS.append('django_test_migrations.contrib.django_checks.AutoNames')
