"""
Test settings for the project.

Used to run tests as fast as possible.

"""

from config.settings.base import *

# DEBUG
# turn debug off so tests run faster
DEBUG = False
TEMPLATES[0]['OPTIONS']['debug'] = False


# SECRET KEY
# NOTE: This key only used for development and testing
SECRET_KEY = env(
    'DJANGO_SECRET_KEY',
    default='test__r=c7otz2gwel5&%ya)%!58f2-jvh6tb-1xor8^6#+4_@kzj7^@',
)


# CACHING
# Speed advantages of in-memory caching without having to run Memcached
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': '',
    },
}


# PASSWORD HASHING
PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']


# TEMPLATES
TEMPLATES[0]['OPTIONS']['loaders'] = [
    (
        'django.template.loaders.cached.Loader',
        [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ],
    ),
]


# DJANGO TEST MIGRATIONS
# install Django check that produces warnings for all migrations with
# autogenerated names
INSTALLED_APPS.append('django_test_migrations.contrib.django_checks.AutoNames')
